<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>strinowa.ico</ApplicationIcon>
    <AssemblyName>strinowa</AssemblyName>
    <RootNamespace>StrinowaWPF</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAPICodePack-Shell" Version="1.1.5" />
  </ItemGroup>
</Project>
